export const datosHeader = {
    titulo: 'Airzone Project'
}

export const confFaseCreacion = {
    mostrarTitulo: true,
    titulo: 'Fase creación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: true,
    mostrarDescripcion: true,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}

export const confFaseRecopilacion = {
    mostrarTitulo: true,
    titulo: 'Fase Recopilación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: true,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}

export const confFaseAnalisis = {
    mostrarTitulo: true,
    titulo: 'Fase análisis',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: true,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseAprobacion = {
    mostrarTitulo: true,
    titulo: 'Fase aprobación ',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAprobacion: true,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFasePlanificacion = {
    mostrarTitulo: true,
    titulo: 'Fase planificación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: true,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseEspecificacion = {
    mostrarTitulo: true,
    titulo: 'Fase Especificación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: true,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseDesarrollo = {
    mostrarTitulo: true,
    titulo: 'Fase desarrollo',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: true,
    mostrarInformeDiseno: true,
    mostrarDocSOO: true,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseValidacionInterna = {
    mostrarTitulo: true,
    titulo: 'Fase validación interna',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: true,
    mostrarDocMantis: true,
    mostrarManual: true,
    mostrarTestProbado: true,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseValidacionCalidad = {
    mostrarTitulo: true,
    titulo: 'Fase validación calidad',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: true,
    mostrarDocMantis: true,
    mostrarManual: true,
    mostrarTestProbado: true,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseFabPrimeraUnidad = {
    mostrarTitulo: true,
    titulo: 'Fase validación interna',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: true,
    mostrarPrimeraUnidadTesteada: false,
    mostrarFechaResponsableSigFase: true
}
export const confFaseValidacionPrimeraUnidad = {
    mostrarTitulo: true,
    titulo: 'Fase validación interna',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarPrimeraUnidadTesteada: true,
    mostrarFechaResponsableSigFase: true
}